### ISSUE TITLE
Cannot build. (Noob here)

### ISSUE THREAD

**Issue by zubair1836** [Yahoo-Mike/recovery_device_lenovo_X505F#1]
Hi, I was trying to build it after reading your instructions but on the first line: `. build/envsetup.sh` I get `No such file or directory`.
I'm using Ubuntu 16.04.
Could you please elaborate on how to build it?

**Comment by Yahoo-Mike** [comment]
All you have to do is [setup the build environment](https://source.android.com/setup/build/initializing#setting-up-a-linux-build-environment). AlaskaLinuxUser has a [video](https://youtu.be/Egb43igdSjA) about this.
